export const USER_INPUT_LOGIN_CHANGED = "USER_INPUT_LOGIN_CHANGED";
export const USER_INPUT_PASSWORD_CHANGED = "USER_INPUT_PASSWORD_CHANGED";
export const USER_ON_LOGIN = "USER_ON_LOGIN";
export const USER_ON_LOGOUT = "USER_ON_LOGOUT";
export const USER_GET_NAME_ID = "USER_GET_NAME_ID";